services:
  postgres:
    image: postgres:16
    container_name: quote-postgres
    environment:
      POSTGRES_DB: quote_db
      POSTGRES_USER: quote_user
      POSTGRES_PASSWORD: quote_pass
    ports:
      - "5432:5432"
    volumes:
      - quote_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: quote-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - quote_rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: quote-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - quote_elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  quote_postgres_data:
  quote_rabbitmq_data:
  quote_elasticsearch_data:

