server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quote_db
    username: quote_user
    password: quote_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2
          max-interval: 5000
        default-requeue-rejected: false

