server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quote_db
    username: quote_user
    password: quote_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2
          max-interval: 5000
        default-requeue-rejected: false

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: quote-flow-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.example.quote_service_eventstore.shared.messaging
        spring.json.value.default.type: com.example.quote_service_eventstore.shared.messaging.DomainEventMessage
        spring.json.use.type.headers: false

      listener:
        ack-mode: record
  app:
    kafka:
      topics:
        quote-events: quote-events
    outbox:
      publisher:
        fixed-delay-ms: 1000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [correlationId=%X{correlationId}] %logger{36} - %msg%n"
